<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="KRISH107" failures="1" tests="2" name="Local Tests" time="356.516" errors="0" timestamp="2024-09-25T14:40:45 IST">
  <testcase classname="sanity.bateel.SanityBateelLiveCheckout" name="testBateelLiveCheckout" time="193.948"/>
  <testcase classname="sanity.bateel.SanityBateelLiveCheckoutWithInvalidCardDetails" name="testBateelLiveCheckoutWithInvalidCard" time="159.434">
    <failure type="java.lang.AssertionError" message="expected [The transaction could not be processed] but found [Your card details are incorrect.]">
      <![CDATA[java.lang.AssertionError: expected [The transaction could not be processed] but found [Your card details are incorrect.]
at page.bateel.BateelLoginCheckoutPage.handleErrorMessage(BateelLoginCheckoutPage.java:132)
at sanity.bateel.SanityBateelLiveCheckoutWithInvalidCardDetails.testBateelLiveCheckoutWithInvalidCard(SanityBateelLiveCheckoutWithInvalidCardDetails.java:51)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testBateelLiveCheckoutWithInvalidCard -->
</testsuite> <!-- Local Tests -->
